channels:
  - conda-forge

dependencies:
  # Python version and pip
  - python=3.10
  - pip

  # Requirements for airavata cerebrum
  - anndata
  - anywidget
  - duckdb
  - fastexcel
  - ipywidgets
  - ipytree
  - jupyter
  - leidenalg
  - nest-simulator
  - numba
  - numpy
  - marimo
  - matplotlib
  - mpi4py
  - openmpi-mpicc
  - openpyxl
  - pandas
  - polars
  - pyarrow
  - pydantic
  - pyqtgraph
  - python-dateutil
  - python-igraph
  - python-jsonpath
  - pyyaml
  - requests
  - scanpy
  - scikit-learn
  - scipy
  - sqlalchemy
  - sqlglot
  - traitlets
  - tqdm

  # PIP dependencies
  - pip:
      - allensdk
      - bmtk
      - neuroanalysis
      - parse
      - git+https://github.com/alleninstitute/abc_atlas_access
      - git+https://github.com/alleninstitute/aisynphys
      - git+https://github.com/srirampc/awitree
